### ISSUE TITLE
IOS checkSendIntentReceived not implemented

### ISSUE THREAD

**Issue by CodeTriager** [calvinckho/capacitor-share-extension#5] opened 2022-11-25 10:33 UTC
Hi
I'm using your plugin within a ionic capacitor app. I just migrated from cordova and needed an alternative for sending files to my app in ios. I followed your instruction and I can send files to my app. The problem is that I get the following error:
`To Native ->  ShareExtension checkSendIntentReceived 32151113
ERROR MESSAGE:  {"errorMessage":"not implemented","code":"UNIMPLEMENTED","data":{},"message":"not implemented"}
⚡️  TO JS {"payload":[]}
ERROR MESSAGE:  {"errorMessage":"not implemented","code":"UNIMPLEMENTED","data":{},"message":"not implemented"}`

Do you got any idea what I'm doing wrong? I'm only using the plugin for ios because i have a different solution for android.

**Comment by calvinckho** [comment] 2022-12-01 23:19
@CodeTriager may I know which npm version of the plugin are you using? Also, which capacitor version?

**Comment by CodeTriager** [comment] 2022-12-02 08:32
I think the issue is that the plugin isn't loaded yet. But I still can't received shared files in the typescript code. The sharing process works, but not the receiving in the app.

This is my ionic info
`Ionic:

   Ionic CLI                     : 5.4.16 (/opt/homebrew/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 5.9.1
   @angular-devkit/build-angular : 0.1100.7
   @angular-devkit/schematics    : 11.2.19
   @angular/cli                  : 11.2.19
   @ionic/angular-toolkit        : 3.1.1

Capacitor:

   Capacitor CLI   : 4.4.0
   @capacitor/core : 4.4.0

Utility:

   cordova-res : 0.15.4
   native-run  : 1.7.1

System:

   NodeJS : v14.20.1 (/opt/homebrew/Cellar/node@14/14.20.1/bin/node)
   npm    : 6.14.17
   OS     : macOS Ventura
`

I'm using version 2.0.0 of the plugin which should be the newest

**Comment by calvinckho** [comment] 2022-12-08 19:58
Because it is an implementation issue and not a bug in the code, I am going to close it for now. You can reopen this issue if you think the problem is related to the source code.

**Closed by calvinckho** 2022-12-08 19:58 UTC
Labels: invalid

**Comment by CodeTriager** [comment] 2022-12-23 10:11
It semms like the Plugin isn't available for some reaseon, but I can't recreate it at the moment anymore.

**Comment by calvinckho** [comment] 2022-12-23 10:31
So it is now working fine in your iOS implementation?

**Comment by CodeTriager** [comment] 2022-12-23 11:04
Yes it’s working fine now!
